LibOfTimetableOfClasses:
  - LibOfTimetableOfClasses/**/*
TimetableOfClasses:
  - TimetableOfClasses/**/*
UnitTestOfTimetableOfClasses:
  - UnitTestOfTimetableOfClasses/**/*
ALARM:
  - any: [*.sln, *.csproj]
