LibOfTimetableOfClasses:
  - LibOfTimetableOfClasses/**/*
TimetableOfClasses:
  - TimetableOfClasses/**/*
UnitTestOfTimetableOfClasses:
  - UnitTestOfTimetableOfClasses/**/*
ALARM:
  - TimetableOfClasses.sln
  - LibOfTimetableOfClasses/LibOfTimetableOfClasses.csproj
  - TimetableOfClasses/TimetableOfClasses.csproj
  - UnitTestOfTimetableOfClasses/UnitTestOfTimetableOfClasses.csproj
