LibOfTimetableOfClasses:
  - LibOfTimetableOfClasses/**/*
TimetableOfClasses:
  - TimetableOfClasses/**/*
UnitTestOfTimetableOfClasses:
  - UnitTestOfTimetableOfClasses/**/*
ALARM:
  - TimetableOfClasses.sln
  - */*.csproj
